# This workflow uses MSBuild and vcpkg to build the project and install dependencies.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout repository and initialize submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Step 2: Setup vcpkg and install dependencies from vcpkg.json
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      id: runvcpkg
      with:
        vcpkgJsonGlob: '**/vcpkg.json'

    # Step 3: Print vcpkg outputs (debugging)
    - name: Print vcpkg outputs
      run: echo "Vcpkg Root: '${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', Triplet: '${{ steps.runvcpkg.outputs.RUNVCPKG_DEFAULT_TRIPLET_OUT }}'"

    # Step 4: Add MSBuild to PATH
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # Step 5: Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore UsefulShell.sln

    # Step 6: Build with MSBuild
    - name: Build with MSBuild
      run: msbuild UsefulShell.sln /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:VcpkgRoot=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}
